# -*- coding: utf-8 -*-
"""coodingloops_positivenumbers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oLISBqsq0JI7eG9-npMfos681e-yfmH1
"""

l1 = [1,2,3.3,4,5.7,'name']
print(l1[2])
for values in l1:print (values)

l1[5][1]

def addition(a, b):  c = a+b
return(c)

type(result)

myList = ["one","two","three"]
for number in myList:
  print (number)

age = 17
if age>18:
 print("We can Vote")
else :
 print ("We cannot Vote")