# -*- coding: utf-8 -*-
"""helloworld.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_3fLWujZZ61vYVtFQXAAcfCdf3a6vErc
"""

print('Hello World')