# -*- coding: utf-8 -*-
"""printpositivenumberspython.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hBsuyGga4ukf0gDIp-DrgirvAh-xRXOw
"""

list1 = [12, -7,5,64, -14]

positive_numbers = [num for num in list1 if num>0]
print ( positive_numbers)

list2 = [12, 14, -95, 3]

positive_numbers = [num for num in list2 if num>0]
print (positive_numbers)